"use client";

import { ImageGeneration } from "@/types/image-generation";
import { useTranslations } from "next-intl";
import moment from "moment";
import downloadPhoto from "@/utils/downloadPhoto";
import { toast } from "sonner";
import Image from "next/image";

interface ImageCardProps {
  generation: ImageGeneration;
}

export default function ImageCard({ generation }: ImageCardProps) {
  const t = useTranslations();

  const handleDownload = async () => {
    if (!generation.generated_image_url) return;
    
    try {
      await downloadPhoto(generation.generated_image_url, `garden-design-${generation.theme}-${generation.uuid}.png`);
      toast.success("Image downloaded successfully!");
    } catch (error) {
      console.error("Error downloading image:", error);
      toast.error("Failed to download image");
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-lg overflow-hidden">
      <div className="aspect-square relative">
        <Image
          src={generation.generated_image_url}
          alt={`${generation.theme} video generated by AI`}
          fill
          className="object-cover"
          loading="lazy"
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
      </div>
      <div className="p-4">
        <div className="flex justify-between items-start mb-2">
          <h3 className="font-semibold text-lg capitalize">{generation.theme}</h3>
          <span className={`px-2 py-1 rounded text-xs ${
            generation.status === 'completed' ? 'bg-green-100 text-green-800' :
            generation.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
            'bg-red-100 text-red-800'
          }`}>
            {generation.status}
          </span>
        </div>
        {generation.elements && (
          <p className="text-sm text-gray-600 mb-2">
            <strong>Elements:</strong> {generation.elements}
          </p>
        )}
        <div className="flex justify-between items-center text-sm text-gray-500">
          <span>{moment(generation.created_at).format("YYYY-MM-DD HH:mm")}</span>
          <span>{generation.credits_used} credits</span>
        </div>
        <div className="mt-3">
          <button
            onClick={handleDownload}
            className="w-full px-3 py-2 bg-blue-500 text-white rounded text-sm hover:bg-blue-600 transition-colors"
          >
            {t("my_images.download")}
          </button>
        </div>
      </div>
    </div>
  );
}